services:
  httpserver:
    ports:
      - "8000:8000"
    image: chatroom:latest
    volumes:
      - ./:/go/src/chatroom
    depends_on:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27018
      MONGODB_URI: mongodb://mongo:27018
      ENV: local
      DD_TRACE_ENABLED: "false"
    networks:
      - backend

  mongo:
    networks:
      - backend
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: chatroom
    command: mongod --port 27018 --setParameter ttlMonitorSleepSecs=1
    ports:
      - "27018:27018"

  redis:
    networks:
      - backend
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

networks:
  backend: